server:
  port: 5000

spring:
  application:
    name: unitTesting

  datasource:
    url: jdbc:postgresql://localhost:5432/unitTest_db
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: update
